// Copyright © 2026 the fmscript2xml-app contributors. Created by Alejandro Riera.
// SPDX-License-Identifier: GPL-3.0-or-later

// Fixture conformance (PLAN §9): every input.txt converts to its expected.xml.
//
// - Public fixtures (Tests/Fixtures/public) always run. Fixtures copied from
//   FileMaker are compared semantically; fixtures generated by the reference
//   implementation (tools/new-fixture.sh) byte for byte. These are recognised
//   by the reference's output: `<?xml version="1.0" ?>` or, for the compact
//   fallback, `<fmxmlsnippet type="FMObjectList"><`.
// - Private fixtures (production scripts, D14) run only when
//   FMSCRIPT_PRIVATE_FIXTURES points at a directory of fixtures. They are
//   never copied into this repository.

import FMScriptKit
import Foundation
import Testing

struct Fixture: CustomTestStringConvertible, Sendable {
    let directory: URL
    var name: String { directory.lastPathComponent }
    var testDescription: String { name }

    var input: String { get throws { try String(contentsOf: directory.appending(path: "input.txt"), encoding: .utf8) } }
    var expected: String { get throws { try String(contentsOf: directory.appending(path: "expected.xml"), encoding: .utf8) } }

    static func list(in base: URL?) -> [Fixture] {
        guard let base,
              let dirs = try? FileManager.default.contentsOfDirectory(at: base, includingPropertiesForKeys: nil)
        else { return [] }
        return dirs
            .filter { !$0.lastPathComponent.hasPrefix(".") }
            .filter {
                FileManager.default.fileExists(atPath: $0.appending(path: "input.txt").path)
                    && FileManager.default.fileExists(atPath: $0.appending(path: "expected.xml").path)
            }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
            .map(Fixture.init)
    }

    static let publicBase = URL(filePath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent()
        .appending(path: "Fixtures/public")

    static let privateBase: URL? = ProcessInfo.processInfo.environment["FMSCRIPT_PRIVATE_FIXTURES"]
        .flatMap { $0.isEmpty ? nil : URL(filePath: ($0 as NSString).expandingTildeInPath) }

    static let publicFixtures = list(in: publicBase)
    static let privateFixtures = list(in: privateBase)
}

/// Converts like the Python fixture tests: continue-on-error.
func convertFixture(_ input: String) -> String {
    Converter().convert(input, policy: .continueOnError).previewXML
}

@Suite("Public fixtures")
struct PublicFixtureTests {
    @Test("There are public fixtures")
    func hasFixtures() {
        #expect(Fixture.publicFixtures.count >= 14)
    }

    @Test("Converts to expected.xml", arguments: Fixture.publicFixtures)
    func fixture(_ fixture: Fixture) throws {
        let generated = convertFixture(try fixture.input)
        var expected = try fixture.expected
        if expected.hasPrefix(#"<?xml version="1.0" ?>"#) || expected.hasPrefix("<fmxmlsnippet type=\"FMObjectList\"><") {
            // Regression fixture written by the reference implementation
            #expect(generated == expected)
        } else {
            // Placeholder IDs like id="<id_of_field>" mark IDs omitted by policy
            expected = expected.replacingOccurrences(of: #"\s+id="<[^"]+>""#, with: "", options: .regularExpression)
            let result = try SemanticComparator.compare(expected: expected, generated: generated)
            #expect(result.isEqual, "\(result.formatted)")
        }
    }
}

@Suite("Private fixtures", .enabled(if: Fixture.privateBase != nil, "Set FMSCRIPT_PRIVATE_FIXTURES to run"))
struct PrivateFixtureTests {
    @Test("Converts to expected.xml", arguments: Fixture.privateFixtures)
    func fixture(_ fixture: Fixture) throws {
        let generated = convertFixture(try fixture.input)
        let result = try SemanticComparator.compare(expected: try fixture.expected, generated: generated)
        #expect(result.isEqual, "\(result.formatted)")
    }
}
